### ISSUE TITLE
open3d not support in docker rolling

### ISSUE THREAD

**Issue by xixioba** [ZhenshengLee/ros2_shm_msgs#1]
Can we eliminate the dependence on open3d? I want to reproduce it in docker, but it's stuck.

**Comment by ZhenshengLee** [comment]
@xixioba thanks for your report.

Of cource we can. 
all we need is an adapter(which is open3d_conversions) between ros pointcloud msg type(here it is point_cloud_8k) and internal data type of a point cloud processing library(here it is open3d)

pcl_conversions can be a good choice, but functions from https://github.com/ros-perception/perception_pcl/blob/ros2/pcl_conversions/include/pcl_conversions/pcl_conversions.h is too much for this demo repo.

PRs are welcomed.

Thanks.

**Comment by ZhenshengLee** [comment]
@xixioba Hi
Now you can compile this package without open3d installed, with #3 being closed.
But pcl_conversions of shm_pc is under development and will be merged in days.

Anyway, you can compile it and check the shm-image-transport demo.

Thanks.

**Comment by ZhenshengLee** [comment]
@xixioba 

Hi, I just realized that you are from China, right? https://github.com/xmake-io/xmake/issues/2300

欢迎加wechat: zhensheng_li 沟通，互相学习共同成长。
