### ISSUE TITLE
Some doubt about rmw_cyclonedds_cpp ?

### ISSUE THREAD

**Issue by lix19937** [ZhenshengLee/ros2_shm_msgs#31]
If I use `export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp`, whether required the user MSG is POD (fied size) or not, the shm img in your demo has std header, which has dynamic field.  

I remembered that to actually use SHM the talker/listener needs to be slightly rewritten to use a fixed size data type such as an unsigned integer/float32_t.

Thanks.

**Comment by ZhenshengLee** [comment]
> the shm img in your demo has std header, which has dynamic field.

It's not std header, its a custom header

https://github.com/ZhenshengLee/ros2_shm_msgs/blob/42fde5f188dc5a55be54718cbb601539d2823815/msg/Image1m.msg#L4

In all shm_msgs, the std::string has been replaced by shm_msgs::string.

https://github.com/ZhenshengLee/ros2_shm_msgs/blob/42fde5f188dc5a55be54718cbb601539d2823815/msg/String.msg#L1-L4

Using char array to replace std string is the core of this repo. see more in https://github.com/eclipse-iceoryx/iceoryx/wiki/2021-08-05-Eclipse-iceoryx-developer-meetup

**Comment by lix19937** [comment]
OHh, sorry I didn't look carefully.  

BTW, ask a multi-topics sync problem, if my MSG has no std header (the header is needed for the timestamp field.), only an `uint64_t stamp`, how to use message filter module ? thanks.
